name: Verify-Sha

on:
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  validate:
    uses: ./.github/workflows/XmlValidation.yml

  verify:
    needs: [validate]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: actions/checkout@v5
        with: 
          ref: ${{ github.event.pull_request.base.sha }}
          path: prev
      - name: Setup ModLinksShaVerifier
        run: |
          wget https://github.com/hk-modding/ModLinksShaVerifier/releases/download/v3.0/linux.zip
          unzip linux.zip
      - name: Verify APILinks SHAs
        run: ./ModlinksShaVerifier prev/ApiLinks.xml ApiLinks.xml
      - name: Verify ModLinks.xml SHAs
        run: ./ModlinksShaVerifier prev/ModLinks.xml ModLinks.xml

